# The west manifest file for upstream Zephyr.
#
# The per-installation west configuration file, .west/config, sets the
# path to the project containing this file in the [manifest] section's
# "path" variable.
#
# You are free to create your own manifest files and put them in any
# repository you want, to create your own custom Zephyr installations.
# For example, you could create a manifest file in your own out of
# tree application directory, which would pull this zephyr repository
# in as an ordinary project.
#
# You can pass your manifest repositories to west init when creating a
# new Zephyr installation. See the west documentation for more
# information.

west:
  url: https://github.com/zephyrproject-rtos/west
  revision: v0.5.7

manifest:
  defaults:
    remote: upstream

  remotes:
    - name: upstream
      url-base: https://github.com/zephyrproject-rtos

  # The initial list of external projects is just Zephyr's net-tools
  # repository, which is useful for running the Zephyr networking
  # stack in QEMU.
  #
  # This will grow over time as external code is migrated into its own
  # repositories.
  projects:
    - name: net-tools
      revision: 30b7efa827b04d2e47840716b0372737fe7d6c92
    - name: tinycbor
      path: modules/lib/tinycbor
      revision: 111f7a215cc4efa49fd03a7835719adca83b4388
    - name: hal_qmsi
      revision: 3179a8e44912a5a05b1cb467870b7e91aedff8d6
      path: modules/hal/qmsi
    - name: fatfs
      revision: df96914dd989907f3a5de4cb95b116c2f305820d
      path: modules/fs/fatfs
    - name: hal_st
      revision: 2f4d2f73fc8d4a494ebd8a12312f7084d2c84ed4
      path: modules/hal/st
    - name: hal_nxp
      revision: 8e4d884d60da14e7d28857d3af37d25de727b171
      path: modules/hal/nxp

  self:
    path: zephyr
    west-commands: scripts/west-commands.yml
