obj-y += core/
obj-$(CONFIG_PLATFORM_IA32_PCI) += platforms/ia32_pci/
obj-$(CONFIG_PLATFORM_IA32) += platforms/ia32/
obj-$(CONFIG_PLATFORM_GALILEO) += platforms/galileo/
obj-$(CONFIG_PLATFORM_ATLASPEAK_X86) += platforms/atlas_peak-x86/
