obj-y += core/
obj-$(CONFIG_PLATFORM_QUARK) += platforms/ia32_pci/
obj-$(CONFIG_PLATFORM_GENERIC_PC) += platforms/ia32/
obj-$(CONFIG_PLATFORM_ATLASPEAK_X86) += platforms/atlas_peak-x86/
obj-$(CONFIG_PLATFORM_MINT_VALLEY) += platforms/mint_valley/
