ccflags-$(CONFIG_QMSI_DRIVERS) +=-I$(CONFIG_QMSI_INSTALL_PATH)/include
obj-$(CONFIG_SPI_INTEL) += spi_intel.o
obj-$(CONFIG_SPI_DW) += spi_dw.o
obj-$(CONFIG_LMT_SPI_QMSI) += spi_qmsi.o
obj-$(CONFIG_SS_SPI_QMSI) += ss_spi_qmsi.o
obj-$(CONFIG_SPI_K64) += spi_k64.o
