name: Self-hosted Build with Clang
on:
  push:
    branches:
      - 'master'
jobs:
  clang-build:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        subset: [1, 2]
    steps:
      - name: Update PATH for west
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: checkout
        uses: actions/checkout@v2

      - name: west setup
        run: |
          west init -l . || true
          west update

      - name: Check Environment
        run: |
          cmake --version
          clang --version

      - name: Run Sanitycheck
        run: |
          source zephyr-env.sh
          #export CLANG_ROOT_DIR=/usr/lib/llvm-10
          export ZEPHYR_TOOLCHAIN_VARIANT=llvm
          ./scripts/sanitycheck --inline-logs -N -v --integration -p native_posix  --subset ${{matrix.subset}}/2 --retry-failed 3

      - name: Upload Unit Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Unit Test Results (Subset ${{ matrix.subset }})
          path: sanity-out/sanitycheck.xml

  publish-test-results:
    name: "Publish Unit Tests Results"
    needs: clang-build
    runs-on: self-hosted
      # the build-and-test job might be skipped, we don't need to run this job then
    if: success() || failure()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -R

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.6
        with:
          check_name: Unit Test Results
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: "**/sanitycheck.xml"
